[FL-3917] Add AppButtonPressRelease request
flipperdevices/flipperzero-protobuf pull request #52
Opened 2024-11-13 10:55 UTC by Astrrra

Enables https://github.com/flipperdevices/flipperzero-firmware/pull/4000

2024-12-02 09:19 UTC, LionZXY submitted a review, later dismissed

2024-12-13 18:41 UTC, gsurkov requested changes
Please update le changelog

2024-12-17 11:48 UTC, gsurkov submitted a review, later dismissed

2024-12-17 11:55 UTC, gornekich approved these changes

2024-12-17 11:55 UTC, merged